version: "3.1"

services:
  postgres:
    restart: always
    container_name: photo_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123!
      
    volumes:
      - photo-data-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  photo-data-volume:


networks:
  local-photo-docker-bridge:
